### ISSUE TITLE
User Interface to the Cisco Threat Intelligence API (CTIA)

### ISSUE THREAD

**Issue by oakmac** [threatgrid/ctia-ui#1]
The [Cisco Threat Intelligence API][1] (CTIA) is a new way of structuring and sharing threat intelligence data.

The purpose of this project is to build an interface to manage and explore CTIA data.

[1]:https://github.com/threatgrid/ctia/

This is way too large and need to be broken down.

I would like to break it down by entity and operation

## Judgements
  - [ ] List and Search Judgements
  - [ ] View a single Judgement
  - [ ] Update a Judgement
  - [ ] Create a New Judgement

## Indicators
  - [ ] List and Search Indicators
  - [ ] View a single Indicator
  - [ ] Update a Indicator
  - [ ] Create a New Indicator

## TTP
  - [ ] List and Search TTPs
  - [ ] View a single TTP
  - [ ] Update a TTP
  - [ ] Create a New TTP
  
## Campaign
  - [ ] List and Search Campaigns
  - [ ] View a single Campaign
  - [ ] Update a Campaign
  - [ ] Create a New Campaign

 
## Actor
  - [ ] List and Search Actors
  - [ ] View a single Actor
  - [ ] Update a Actor
  - [ ] Create a New Actor
